import ...

/**
 *
 * @author Nirbhay Pundir
 */
public class LoginGUI extends javax.swing.JFrame {

    Utility u;

    public LoginGUI() {
        u = new Utility();
        initComponents();
        u.setCorners(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do not modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    // <editor-fold defaultstate="collapsed" desc="Generated Code">

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) { // GEN-FIRST:event_btnCloseMouseClicked
        System.exit(status);
    }// GEN-LAST:event:event_btnCloseMouseClicked

    private void btnCloseMouseEntered(java.awt.event.MouseEvent evt) { // GEN-FIRST:event_btnCloseMouseEntered
        btnClose.setIcon(u.imageCloseh);
    }// GEN-LAST:event:event_btnCloseMouseEntered

}
